[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "migration"
path = "src/main.rs"

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
clap = { version = "4.0", features = ["derive", "env"] }
url = "2.5"
sea-orm = { version = "1.1.0", features = ["runtime-async-std-rustls", "sqlx-postgres"] }

[dependencies.sea-orm-migration]
version = "1.1.0"
features = [
  "runtime-async-std-rustls",
  "sqlx-postgres",
]
