//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

pub use super::turbo_togel_draw_result::Entity as TurboTogelDrawResult;
pub use super::turbo_togel_draw_shedule::Entity as TurboTogelDrawShedule;
