[workspace.package]
version = "0.1.0"
authors = ["j50301m <j50301m@yahoo.com.tw>"]
edition = "2024"
repository = "https://github.com/j50301m/aura_rs"


[workspace]
resolver = "3"
members = [
    "common",
    "migration",
    "services/gameapi",
    "services/gamecore",
    "services/drawing",
]

[workspace.dependencies]
common = {path ="common"}
actix-web = "4"
sea-orm = { version = "1.1.15", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
anyhow = "1"
thiserror = "2"
cfgloader_rs = "1.0.1"
tokio-cron-scheduler = "0.14.0"
tokio = {version = "1", features = ["full"]}
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.10"
rand = "0.9"
tracing = "0.1"
serde_json = "1.0"
redis = { version = "0.32.5", features = ["tokio-comp","connection-manager"] }
tracing-subscriber = "0.3"
