[package]
name = "gameapi"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = {workspace = true}
anyhow = {workspace = true}
thiserror = {workspace = true}

[[bin]]
name = "gameapi"
cfgloader = { path = "../cfgloader" }
cfgloader_derive = { path = "../cfgloader_derive" }
# cfgloader = {workspace = true}
# cfgloader_derive = {workspace = true}