[package]
name = "drawing"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
common = {workspace = true}
sea-orm = {workspace = true}
tokio = {workspace = true}
tokio-cron-scheduler = {workspace = true}
cfgloader_rs = {workspace = true}
anyhow = {workspace = true}
chrono = {workspace = true}
chrono-tz = {workspace = true}
rand = {workspace = true}
tracing = {workspace = true}
serde_json = {workspace = true}
redis = { version = "0.32", features = ["tokio-comp"] }
uuid = { version = "1.0", features = ["v4"] }
